### ISSUE TITLE
Event object is missing property for "thread_participant"

### ISSUE THREAD

**Issue by kmk713** [GetStream/stream-chat-net#10]
Hi, I'm using stream-chat-net to parse "reply' type messages in my webhook.

Events for message.new contain "thread_participant" property if the message type is a reply.

However, the StreamChat.Event class is missing this property and hence this information gets lost while parsing.

Here's an example of thread reply event that gets captured by webhook:

![image](https://user-images.githubusercontent.com/31493089/77123004-da208800-6aa3-11ea-984b-59cb904772f5.png)

**Comment by ferhatelmas** [comment]
@kmk713 `Event` implements `CustomDataBase`, which populates a generic dictionary.
You can retrieve optional data from `event.GetData("your_key")`.
