### ISSUE TITLE
Receiving "api_key not provided" after 2.0.0 update

### ISSUE THREAD

**Issue by andrewgierens** [GetStream/stream-chat-net#115]
Hello, I am receiving the following error after the 2.0.0 update (including latest) `StreamChat.Exceptions.StreamChatException: UpdateUsers failed with error: "api_key not provided"`

I have downgraded to 1.1.1, and can confirm that the issue is not present in lower versions.

Code to replicate is below:

```
public async Task<IEnumerable<User>> CreateUsers(StreamCreateUser[] usersToCreate)
{
	var factory = new StreamClientFactory("KEY", "SECRET");
	var userClient = factory.GetUserClient();
	
	var result = await userClient.UpsertManyAsync(usersToCreate.Select(z => new UserRequest
	{
		Id = z.UserId,
		Role = Role.User,
		Name = $"{z.PreferredName ?? z.FirstName} {z.LastName}"
	}));
	return result?.Users.Select(z => z.Value);
}
```

I have not had a chance to debug this yet, but if I am doing something wrong, please let me know

**Comment by andrewgierens** [comment]
Thanks for the reply @ferhatelmas  - Our api_key is `9xwubzp2rvee`

I have written a test client for this and am still receiving this error when using the latest version. This is the exact code snippet that is running in the test client

```
public static void Main(string[] args)
{
	var factory = new StreamClientFactory("9xwubzp2rvee",  "privateKey");
	var userClient = factory.GetUserClient();

	var usersToCreate = new List<(string UserId, string PreferredName, string FirstName, string LastName)>();
	usersToCreate.Add(("test-api-4.8", "Test", "Test", "Test"));
	
	var result = userClient.UpsertManyAsync(usersToCreate.Select(z => new UserRequest
	{
		Id = z.UserId,
		Role = Role.User,
		Name = $"{z.PreferredName ?? z.FirstName} {z.LastName}"
	})).Result;
	
	var test = result?.Users.Select(z => z.Value);
}
```

Framework: .NETFramework v4.8
Package: stream-chat-net v2.1.0

**Comment by ferhatelmas** [comment]
Thanks, that explains tests are only working under core. Will give a further look.

**Comment by andrewgierens** [comment]
Great - thanks. Let me know if you need anymore info / need me to test something

**Comment by sierpinskid** [comment]
@andrewgierens I was able to reproduce your case in .NET Framework 4.8 and the fix is on the way

**Comment by ferhatelmas** [comment]
Thank you @andrewgierens for spotting & @sierpinskid for fixing. 👍🏻

**Comment by andrewgierens** [comment]
Thanks team - Working perfectly now.
