### ISSUE TITLE
Include channel name in channel query API

### ISSUE THREAD

**Issue by BorisFilinovAtSpark** [GetStream/stream-chat-net#121]
Hi, I am trying to obtain a list of channels via the QueryChannelsAsync method.
The querying itself works just fine, but I can't find a way to view a channel's name in the ChannelGetResponse object.
Is there a workaround for this?

**Comment by ferhatelmas** [comment]
It's a custom property so it goes to `Data` property of channel so you can read it via `channel.Data.GetData<string>("name")`
