### ISSUE TITLE
Error converting value "deleted" to type 'StreamChat.Models.MessageRequestType'

### ISSUE THREAD

**Issue by rjacquemin** [GetStream/stream-chat-net#133]
We are using `stream-chat-net` v 2.3.0
we are receiving  events from SQS integration

Since couple of weeks we are receiving a new value  `deleted`   for   `MessageRequestType`  
This new value triggers the following error when deserializing 
``` 
Error converting value "deleted" to type 'StreamChat.Models.MessageRequestType'. Path 'message.type', line 1, position 326.
```
   
After checking the code in you .net client  
https://github.com/GetStream/stream-chat-net/blob/910df4da198bdf0145f4d9cb0b0c81b0c6258a1c/src/Models/MessageRequest.cs#L10

It might be related to latest change about system message  
https://github.com/GetStream/stream-chat-net/commit/44e5cb411cbda0d01d660393b999e5d09830c533

This is a new value that we received from the events queue ...   
What are the impacts ? 
All delete events are failing ?  
or just the system messages ? 

Can you double check if the system message feature has a side effect on the `deleted`  messages

thanks in advance

**Comment by sierpinskid** [comment]
Hi,
thank you for all of the details.

The `StreamChat.Models.MessageRequestType` is only used by the `StreamChat.Models.MessageRequest` model. However, when handling the received events you should be deserializing into a `StreamChat.Models.Message` type of object that uses `string` for a `type` field. The `MessageRequest` is only used when sending or updating the messages. 

Please let me know if this resolved your issue.

Kind regards,
Daniel

**Comment by rjacquemin** [comment]
> Hi, thank you for all of the details.
> 
> The `StreamChat.Models.MessageRequestType` is only used by the `StreamChat.Models.MessageRequest` model. However, when handling the received events you should be deserializing into a `StreamChat.Models.Message` type of object that uses `string` for a `type` field. The `MessageRequest` is only used when sending or updating the messages.
> 
> Please let me know if this resolved your issue.
> 
> Kind regards, Daniel

our integration is pretty simple    

![image](https://github.com/GetStream/stream-chat-net/assets/12820060/dfdc304d-906e-4992-9da3-76a7b74ad73a)

we just deserialize SQS Event  into the  `stream-sdk` Event  object  
https://github.com/GetStream/stream-chat-net/blob/master/src/Models/Event.cs

As we are listening    different types of events 
- message 
- channel 

we can not serialize only `Message` event type

**Comment by sierpinskid** [comment]
Thank you for this information. I now see what the issue is. I'll look into it and get back to you.

**Comment by sierpinskid** [comment]
@rjacquemin the [Event ](https://github.com/GetStream/stream-chat-net/blob/3b41804ffe8f8e731b18608f91570530b53e94d4/src/Models/Event.cs#L8) model was designed to be used as a part of request when using the `IEventClient.SendEventAsync` endpoint. That's why it might fail when used for received events deserialization.

The `2.5.0` release introduces the [EventResponse](https://github.com/GetStream/stream-chat-net/blob/3b41804ffe8f8e731b18608f91570530b53e94d4/src/Models/Event.cs#L35) model that should work properly for received JSON events. 

Please upgrade the SDK, and change the deserialization logic to use the `EventResponse`:

```csharp
JsonConvert.DeserializeObject<EventResponse>(message.Body);
```
and let me know if you have any other issues.
