### ISSUE TITLE
Hard delete option missing from SDK

### ISSUE THREAD

**Issue by shodgetts** [GetStream/stream-chat-net#18]
We assumed stream-chat-net is used to implement a server side client that can hard delete messages via message id.
But we found that 

(https://github.com/GetStream/stream-chat-net/blob/3f1ef62e71b489c47e5c01ff56fea6b4b7141372/src/stream-chat-net/Client.cs#L263)
public async Task<Message> DeleteMessage(string messageID)
only accept one argument but not the second argument like we found in stream-chat-js

(https://github.com/GetStream/stream-chat-js/blob/f74e3f0d6986363c3b457e0e088e6d47c3f711c7/src/client.ts#L1861)
async deleteMessage(messageID: string, hardDelete?: boolean) 

gz#6181

**Comment by penghouho** [comment]
I made a pull request to support this missing feature.
https://github.com/GetStream/stream-chat-net/pull/17
Thanks.

**Comment by ferhatelmas** [comment]
fixed by #17
