### ISSUE TITLE
When will v0.4.4 release be available via nuget?

### ISSUE THREAD

**Issue by ntziolis** [GetStream/stream-chat-net#19]
@ferhatelmas I see you created a new release with multi location support which is awesome. Do you have an ETA on when this will be pushed to nuget? 

Note:
- One of our clients is currently prevented from going live due to privacy concerns.
- We cant use the binary package as their internal policies only allow third party packages when installed via nuget.

**Comment by ferhatelmas** [comment]
@ntziolis sorry for the inconvenience, will release today.

**Comment by ferhatelmas** [comment]
Due to some problems, need to skip some versions and publish 0.4.7

https://www.nuget.org/packages/stream-chat-net/0.4.7

Setup is done, releases should come regularly from now on.

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/6368'>Zendesk ticket #6368</a>:<br><br>This is released so closing.
