### ISSUE TITLE
Parsing the webhook body

### ISSUE THREAD

**Issue by gallivantor** [GetStream/stream-chat-net#2]
What is the recommended approach for parsing the webhook body into an object?
Currently I have this code in my webhook API controller:
```
var signature = request.Headers["X-Signature"];
if (!_client.VerifyWebhook(body, signature)) {
  throw new Exception("invalid signature");
}
var jsonBody = JsonConvert.DeserializeObject(body);
```
Looking at the StreamChat library code, it looks like the obvious thing I should do next is:
`var webhookEvent = Event.FromJObject(jsonBody);`
but this method is marked `internal` so it's not possible.

How are we supposed to achieve this?

**Comment by gallivantor** [comment]
Hi, when is the next nuget package release planned to incorporate this change?

**Comment by bogdan-getstream** [comment]
We had released fix for the issue, closing ticket
