### ISSUE TITLE
Ban user usage confusion

### ISSUE THREAD

**Issue by hima-Megahed** [GetStream/stream-chat-net#20]
Hello Stream dev team,

I was using stream chat net in my latest web chat app, and wanted to use **Ban** and **UnBan** features.
So in the readme file as you documented there, BanUser only accepts 3 parameters unlike me it accepts 4 parameters the first one called "**targetID**" which I don't know what is this should be.

Anyone could guide me I would be thankful?

gz#6728

**Comment by ahmeddahy** [comment]
@keyneston @gumuz @tbarbugli  @pterk 
These are the parameters of "ban user" end point.
I can't understand the usage of them.
Can you please explain for us what is the meaning or more details about each parameter of them?
![image](https://user-images.githubusercontent.com/19478517/97192187-5a346c00-17b0-11eb-850a-5a3da8c46b43.png)
![image](https://user-images.githubusercontent.com/19478517/97192239-64ef0100-17b0-11eb-9ba5-29378c1371f3.png)

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6728'>Zendesk ticket #6728</a>:<br><br>Hello, what is the problem? Are you receiving an error or are unable to use this feature?

**Comment by ahmeddahy** [comment]
The problem is I don't know exactly what should I provide in the body of the banning request can you illustrate the body fields for me ?
I am unable to use this feature.
Thanks.

**Comment by ferhatelmas** [comment]
```c#
// last argument is optional for expiration in minutes
channel.BanUser(bannedUser.ID, bannerUser.ID, "a reason to ban", 5) 
```
