### ISSUE TITLE
Can't Remove channel Member

### ISSUE THREAD

**Issue by hima-Megahed** [GetStream/stream-chat-net#21]
Hello getstream team,

I'm facing trouble while removing a user from channel, fyi this user is the creator of the channel.

So previously I was able to leave the channel that I created normally now I find myself still a member in channel after removing my self from the channel.

Is there any business changes that changed the way of managing removing channel members?

@keyneston @gumuz @tbarbugli @pterk @tschellenbach @shodgetts @sirio7g 

gz#6923

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/6923'>Zendesk ticket #6923</a>:<br><br>Hi there,

Thanks for getting in touch.
Our development team is currently working on a patch to fix this issue. It should be live by the end of the day, in the meantime, we might be able to remediate the problem directly by acting directly on your app. Can you share your app Id related please?

Best regards,

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/6923'>Zendesk ticket #6923</a>:<br><br>Hi there,

Thanks for getting in touch.
Our development team is currently working on a patch to fix this issue. It should be live by the end of the day, in the meantime, we might be able to remediate the problem directly by acting directly on your app. Can you share your app Id related please?

Best regards,

**Comment by hima-Megahed** [comment]
Hello @shodgetts Thanks for your fast reply.

Our AppId is : 90043

Actually I'm facing other problems in leaving One To One chats although it was working just fine 2 days ago, Is that related to this issue?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6923'>Zendesk ticket #6923</a>:<br><br>Hello, Yes, this issue should now be resolved. Sorry for the inconvenience.

**Comment by ferhatelmas** [comment]
Closing the issue, please reply if still an issue.
