### ISSUE TITLE
Teams support

### ISSUE THREAD

**Issue by hognevevle** [GetStream/stream-chat-net#23]
Hello,

In reference to the docs on https://getstream.io/chat/docs/multi_tenant_chat/?language=c_sharp 

While I can in fact enable multitenant mode using UpdateAppSettings, it seems that stream-chat-net does not yet support the "team" properties of users or channels. 

Javascript equivalents:
`client.updateUser({id, teams: ["red", "blue"]});`
`client.channel("messaging", "red-general", {team: "red"}).create()`

Any way that these features can be added to the .NET library?

gz#7802

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out. Indeed, the .net client should support multi-tenancy mode.
Can you share your code for updating the user and creating the channel with the .Net client please?

Thanks in advance.
Best regards,

**Comment by hognevevle** [comment]
@SeniYG  As far as I can see, there is no way to provide a team when updating a user currently.

```var user = await client.Users.Update(new User
            {
                Role = "channel_member",
                ID = Guid.NewGuid().ToString(),
                // should be a Teams property here as well
            });```

As for channels, there is a GenericData object I can pass in, although I'm not sure if this is doing the equivalent of the javascript code. 

            ```var teamName = "foo";
            var genericData = new GenericData();
            genericData.SetData("team", teamName);
            
            var channel = client.Channel("commerce", $"{teamName}-{Guid.NewGuid().ToString()}", genericData);```

**Comment by IvanBAtSpark** [comment]
@hognevevle there is a workaround:
```
    class YourOwnUser : StreamChat.User
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "teams")]
        public string[] Teams { get; set; }
    }
```
Setting `team` prop for a channel via GenericData helps.
But this should be supported on a library level, not via workarounds.

**Comment by hognevevle** [comment]
@IvanBAtSpark Thank you very much for sharing that workaround! (And yes, I totally agree)

**Comment by ferhatelmas** [comment]
@hognevevle @IvanBAtSpark `CustomDataBase` is also in `User` and a few other classes so you can do the same thing.

`user.SetData("teams", new string[] {"red"});`
