### ISSUE TITLE
Multi-Tenancy is not supported for .NET client

### ISSUE THREAD

**Issue by DmitryDAtSpark** [GetStream/stream-chat-net#24]
Hello, 

According to https://getstream.io/chat/docs/multi_tenant_chat/?language=js, .NET client should support multi-tenancy feature.

We successfully enabled multitenancy for app via the library https://github.com/GetStream/stream-chat-net, but we can't set a "team" property for a user or a channel via this lib.

When do you plan to deliver this feature for .NET client? 

gz#7811

**Comment by hognevevle** [comment]
#23

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7811'>Zendesk ticket #7811</a>:<br><br>Hello, Totally understandable. What is your Stream org/appID please?

**Comment by DmitryDAtSpark** [comment]
> Agent comment from Stephen Hodgetts in [Zendesk ticket #7811](https://getstream.zendesk.com/agent/tickets/7811):
> 
> Hello, Totally understandable. What is your Stream org/appID please?

ProgressRetail
APP ID: 98681

**Comment by ferhatelmas** [comment]
@DmitryDAtSpark since it's an optional feature, supported by custom data base as follows:

```c#
channel.SetData("team", "red");
user.SetData("teams", new string[] { "red", "blue" });
```
