### ISSUE TITLE
support silent messages

### ISSUE THREAD

**Issue by skaegebein** [GetStream/stream-chat-net#39]
any plans to support [silent messages](https://getstream.io/chat/docs/dotnet-csharp/silent_messages/?language=csharp)?

gz#11930

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/11930'>Zendesk ticket #11930</a>:<br><br>Hi there,

Thanks for getting in touch, we'll get back to you as soon as we can.
<br><p><em><small>°°°</small></em></p>
