### ISSUE TITLE
support hiding a channel

### ISSUE THREAD

**Issue by skaegebein** [GetStream/stream-chat-net#40]
any plans to support [hiding a channel](https://getstream.io/chat/docs/dotnet-csharp/channel_delete/?language=csharp#hiding-a-channel)?

gz#11931

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/11931'>Zendesk ticket #11931</a>:<br><br>Hi there,

Thanks for getting in touch, we'll get back to you as soon as we can.
<br><p><em><small>°°°</small></em></p>
