### ISSUE TITLE
channel partial update support

### ISSUE THREAD

**Issue by cconfer-livly** [GetStream/stream-chat-net#41]
Unless I'm missing something, it doesn't appear as though the sdk supports the partial update of a channel.  My specific use case would be updating a custom data value. 

gz#12073

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/12073'>Zendesk ticket #12073</a>:<br><br>Hi,

Thanks for reaching out! I'll look into this for you and get back to you shortly. Please let me know if you have any other questions in the meantime.

Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by cconfer-livly** [comment]
> Agent comment from Ryan Kavanaugh in [Zendesk ticket #12073](https://getstream.zendesk.com/agent/tickets/12073):
> 
> Hi,
> 
> Thanks for reaching out! I'll look into this for you and get back to you shortly. Please let me know if you have any other questions in the meantime.
> 
> Best,
> Ryan
> 
> 
> _°°°_

thanks

**Comment by phenry20** [comment]
Any updates?

**Comment by ferhatelmas** [comment]
It's coming today

**Comment by RaduTudorIon** [comment]
Thank you!

**Comment by RaduTudorIon** [comment]
When will the nuget package update come?

**Comment by ferhatelmas** [comment]
Thanks for the ping and patience. Should be ready by Friday.

**Comment by peterdeme** [comment]
PR: https://github.com/GetStream/stream-chat-net/pull/69

**Comment by ferhatelmas** [comment]
resolved in #69

**Comment by peterdeme** [comment]
Available in 0.24.0
