### ISSUE TITLE
Channel ban user method deprecated?

### ISSUE THREAD

**Issue by RaduTudorIon** [GetStream/stream-chat-net#46]
Is this part of the documentation up to date? 
```
//add a ban with a timeout
await chan.BanUser(june.ID, "Being a big jerk", 4);
```
I tried this recently and it throws an error, the method from the current nugget package has this signature: BanUser(string targetID, string id, string reason, int timeoutMinutes = 0);

I assume targetId is the user you want to ban, id is the user that is banning. I tried the method from the package with an id of an admin and a member to ban and it returns OK, but no changes are made to the member

**Comment by SeniYG** [comment]
Hi,

Thanks for bringing this to our attention. Indeed, you are right, as this .NET client is a server-side client, the id is required so the API knows on behalf of which user the ban operation is performed. 
This Readme example needs to be corrected. I've submitted a PR for this, one of our engineers will merge it soon.

Best regards,
Seni

**Comment by RaduTudorIon** [comment]
![image](https://user-images.githubusercontent.com/15893272/121892222-20a37780-cd25-11eb-835a-24685cf8851c.png)
The call is definitely made because it affects the rate limits in the admin dashboard. The id of the user who is banning in my case is a global admin

**Comment by RaduTudorIon** [comment]
> 
> 
> Hi,
> 
> Thanks for bringing this to our attention. Indeed, you are right, as this .NET client is a server-side client, the id is required so the API knows on behalf of which user the ban operation is performed.
> This Readme example needs to be corrected. I've submitted a PR for this, one of our engineers will merge it soon.
> 
> Best regards,
> Seni

 The call is definitely made because it affects the rate limits in the admin dashboard. The id of the user who is banning in my case is a global admin 

![image](https://user-images.githubusercontent.com/15893272/121892451-711ad500-cd25-11eb-8cba-398d9687deb5.png)

Can you also check if the ban function works?

**Comment by SeniYG** [comment]
Hi,

What the behaviour after the ban call is made? Are you still able to send messages with the banned user?

Best,

**Comment by RaduTudorIon** [comment]
![image](https://user-images.githubusercontent.com/15893272/121893712-f783e680-cd26-11eb-8f0c-a931352e99a5.png)
I tried to ban this user. It appears the member's banned status is not changing, so he can still send messages, this picture is after the banUser method was called. So after the banUser is called, the user is is still `banned:false`  

I made the call as the user below who is an admin 
![image](https://user-images.githubusercontent.com/15893272/121894000-4af63480-cd27-11eb-8990-9536e569cff1.png)

I also tried this one
![image](https://user-images.githubusercontent.com/15893272/121894100-66f9d600-cd27-11eb-9064-10726bb6daa1.png)

After both calls the user 63021 is still `banned:false`. Both calls return no error

**Comment by RaduTudorIon** [comment]
> 
> 
> Hi,
> 
> What the behaviour after the ban call is made? Are you still able to send messages with the banned user?
> 
> Best,

So I made some tests, _client.Users.Ban works for a global ban of a user, but channel.BanUser doesn't seem to work if you want to ban a user just from one channel

**Comment by ferhatelmas** [comment]
@RaduTudorIon right, I will add the missing part for channels / ip banning.

**Comment by RaduTudorIon** [comment]
Thank you!

**Comment by RaduTudorIon** [comment]
> 
> 
> @RaduTudorIon right, I will add the missing part for channels / ip banning.

Thank you!

**Comment by peterdeme** [comment]
Introduced a lot of improvements in https://github.com/GetStream/stream-chat-net/pull/92
