### ISSUE TITLE
MembersPagination doesn't work. Always retun 100.

### ISSUE THREAD

**Issue by minchul-park** [GetStream/stream-chat-net#48]
var queryParams = new StreamChat.ChannelQueryParams();
queryParams.MembersPagination = new StreamChat.PaginationParams()
{
    Offset = 10,
    Limit = 10
};

var channelState = await channel.Query(queryParams);

// always return 100
var memberCount =  channelState.Members.Count;

gz#12815

**Comment by ferhatelmas** [comment]
Top level `limit`/`offset` is for channels you're querying. Set `MembersPagination`/`MessagesPagination` properties of `ChannelQueryParams` to specify how many members and messages respectively you want to load in each returned channel.

**Comment by minchul-park** [comment]
`queryParams.State = true;`

It works good after setting above.
Thank you.
