### ISSUE TITLE
How to export the channel in .Net

### ISSUE THREAD

**Issue by RaduTudorIon** [GetStream/stream-chat-net#50]
In the documentation for the .Net SDK (https://getstream.io/chat/docs/dotnet-csharp/exporting_channels/?language=csharp) there is a section for exporting channels but the code example is in javascript, and the client method for .Net doesn't have an exportChannel . Currently I cannot find any way to export the chat from a channel via back-end. Is there a way to do this? It is especially useful since you probably need to parse it to show that data in a meaningful way, is ChannelState.Messages an approximation of what the exportChannel does?

gz#13512

**Comment by ferhatelmas** [comment]
This feature is missing, we will add it ASAP.

**Comment by RaduTudorIon** [comment]
> 
> 
> This feature is missing, we will add it ASAP.

Thank you! It is very much needed
