### ISSUE TITLE
message partial update support

### ISSUE THREAD

**Issue by hognevevle** [GetStream/stream-chat-net#57]
Currently this SDK seems to only support `UpdateMessage`, which when used seems to clear all fields that are not supplied in the MessageInput (at least some of them, e.g. the message text is lost unless you supply it). 

Could we please get a `UpdateMessagePartial` or similar?

Similar to https://github.com/GetStream/stream-chat-net/issues/41

**Comment by RaduTudorIon** [comment]
That would be useful

**Comment by ferhatelmas** [comment]
fixed in #77

**Comment by peterdeme** [comment]
Available in 0.24.0
