### ISSUE TITLE
Users are able to see several last message in messaging and team channels they don't belong to

### ISSUE THREAD

**Issue by NikAtSpark** [GetStream/stream-chat-net#62]
Hi!

We have an issue that any user (even if NOT a member of the particular messaging channel) is able to see that exact channel and at least several messages in it.
Also looks like there is an issue with applying permissions to that particular case:
- I've tried using the default policy set, and it has shown me the last several messages (in each channel the number is distinct) and throws an access error when trying to get more messages
-  I've tried restricting permissions more and more and tried even disabling access to All roles entirely. But still, I see the same thing: all channels are visible, and the last set of messages are visible as well.

This is a privacy violation issue, as users could see messages that do not belong to their access scope (chats of other people Not including the user using that).

Current permissions are set to the following:
`[
	{
		"action": "Deny",
		"name": "deny all policy",
		"resources": [
			"*"
		],
		"roles": [
			"*"
		],
		"owner": false,
		"priority": 1
	}
]`

Request example:
`POST https://chat-us-east-1.stream-io-api.com/channels?user_id=************&api_key=************&connection_id=************`
`{
  "filter_conditions": { "type": "messaging" },
  "sort": [
    {
      "field": "has_unread",
      "direction": -1
    },
    {
      "field": "last_message_at",
      "direction": -1
    }
  ],
  "state": true,
  "watch": true,
  "presence": false,
  "limit": 30
}`

Response (cleaned up, in order not to include 4K lines long response, including personal data) None of the users in members is my user, and permissions are set to deny everything:
`{
"channels":[...
   {
      "channel": {
        "id": "!members-ieHLMtf2IgHJ8FeCzIsBzhFviClk7HucKmxykBrnNz4",
        "type": "messaging",
        "cid": "messaging:!members-ieHLMtf2IgHJ8FeCzIsBzhFviClk7HucKmxykBrnNz4",
        "last_message_at": "2021-06-08T12:47:10.55206Z",
        "created_at": "2021-06-08T12:47:07.965299Z",
        "updated_at": "2021-06-08T12:47:07.965299Z",
        "created_by": {
          "id": "5deb6667-df00-4672-89c6-02600bc16d25",
          "role": "user",
          "created_at": "2021-01-21T12:46:50.88392Z",
          "updated_at": "2021-04-08T13:50:20.335871Z",
          "last_active": "2021-06-08T12:45:18.133931Z",
          "banned": false,
          "online": false,
          "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
          "name": "Emails7 Changer7",
          "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/a99648b5-16d9-40d0-84cd-04cc842bc7bc"
        },
        "frozen": false,
        "disabled": false,
        "member_count": 2,
        "config": {
          "created_at": "2021-11-03T18:06:24.291235Z",
          "updated_at": "2021-11-03T18:26:17.643261Z",
          "name": "messaging",
          "typing_events": true,
          "read_events": true,
          "connect_events": true,
          "search": true,
          "reactions": true,
          "replies": true,
          "quotes": true,
          "mutes": true,
          "uploads": true,
          "url_enrichment": true,
          "custom_events": true,
          "push_notifications": true,
          "message_retention": "infinite",
          "max_message_length": 5000,
          "automod": "disabled",
          "automod_behavior": "flag",
          "blocklist_behavior": "flag",
          "automod_thresholds": {},
          "commands": [
            {
              "name": "giphy",
              "description": "Post a random gif to the channel",
              "args": "[text]",
              "set": "fun_set"
            }
          ]
        },
        "team": "1e033efd-577a-42c1-a36d-83a05bc0fab2",
        "own_capabilities": [ "search-messages", "send-typing-events" ],
        "hidden": false
      },
      "messages": [
        {
          "id": "5deb6667-df00-4672-89c6-02600bc16d25-121d81a3-43ec-4e85-b328-3dc8f9718cca",
          "text": "teewt",
          "html": "\u003cp\u003eteewt\u003c/p\u003e\n",
          "type": "regular",
          "user": {
            "id": "5deb6667-df00-4672-89c6-02600bc16d25",
            "role": "user",
            "created_at": "2021-01-21T12:46:50.88392Z",
            "updated_at": "2021-04-08T13:50:20.335871Z",
            "last_active": "2021-06-08T12:45:18.133931Z",
            "banned": false,
            "online": false,
            "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
            "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/a99648b5-16d9-40d0-84cd-04cc842bc7bc",
            "name": "Emails7 Changer7"
          },
          "attachments": [],
          "latest_reactions": [],
          "own_reactions": [],
          "reaction_counts": {},
          "reaction_scores": {},
          "reply_count": 0,
          "cid": "messaging:!members-ieHLMtf2IgHJ8FeCzIsBzhFviClk7HucKmxykBrnNz4",
          "created_at": "2021-06-08T12:47:10.55206Z",
          "updated_at": "2021-06-08T12:47:10.55206Z",
          "shadowed": false,
          "mentioned_users": [],
          "silent": false,
          "pinned": false,
          "pinned_at": null,
          "pinned_by": null,
          "pin_expires": null
        }
      ],
      "pinned_messages": [],
      "watcher_count": 2,
      "read": [
        {
          "user": {
            "id": "bfc34d55-895b-47da-84e4-306f4e532a94",
            "role": "user",
            "created_at": "2020-12-10T14:20:38.887844Z",
            "updated_at": "2021-04-08T13:59:09.74671Z",
            "last_active": "2021-09-06T11:57:24.935509Z",
            "banned": false,
            "online": false,
            "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
            "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/df96d4ad-e884-49f2-8032-70ce3caeb414",
            "name": "***** ******"
          },
          "last_read": "2021-06-08T12:48:22.079512064Z",
          "unread_messages": 0
        },
        {
          "user": {
            "id": "5deb6667-df00-4672-89c6-02600bc16d25",
            "role": "user",
            "created_at": "2021-01-21T12:46:50.88392Z",
            "updated_at": "2021-04-08T13:50:20.335871Z",
            "last_active": "2021-06-08T12:45:18.133931Z",
            "banned": false,
            "online": false,
            "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
            "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/a99648b5-16d9-40d0-84cd-04cc842bc7bc",
            "name": "***** ******"
          },
          "last_read": "2021-06-08T12:49:11.379953664Z",
          "unread_messages": 0
        }
      ],
      "members": [
        {
          "user_id": "5deb6667-df00-4672-89c6-02600bc16d25",
          "user": {
            "id": "5deb6667-df00-4672-89c6-02600bc16d25",
            "role": "user",
            "created_at": "2021-01-21T12:46:50.88392Z",
            "updated_at": "2021-04-08T13:50:20.335871Z",
            "last_active": "2021-06-08T12:45:18.133931Z",
            "banned": false,
            "online": false,
            "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
            "name": "***** ******",
            "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/a99648b5-16d9-40d0-84cd-04cc842bc7bc"
          },
          "created_at": "2021-06-08T12:47:07.968832Z",
          "updated_at": "2021-06-08T12:47:07.968832Z",
          "banned": false,
          "shadow_banned": false,
          "role": "owner",
          "channel_role": "channel_member"
        },
        {
          "user_id": "bfc34d55-895b-47da-84e4-306f4e532a94",
          "user": {
            "id": "bfc34d55-895b-47da-84e4-306f4e532a94",
            "role": "user",
            "created_at": "2020-12-10T14:20:38.887844Z",
            "updated_at": "2021-04-08T13:59:09.74671Z",
            "last_active": "2021-09-06T11:57:24.935509Z",
            "banned": false,
            "online": false,
            "teams": [ "1e033efd-577a-42c1-a36d-83a05bc0fab2" ],
            "image": "https://prodprtseafilestorastg.blob.core.windows.net/avatars/df96d4ad-e884-49f2-8032-70ce3caeb414",
            "name": "***** ******"
          },
          "created_at": "2021-06-08T12:47:07.968832Z",
          "updated_at": "2021-06-08T12:47:07.968832Z",
          "banned": false,
          "shadow_banned": false,
          "role": "member",
          "channel_role": "channel_member"
        }
      ],
      "membership": null
    }
...],
"duration": "40.49ms"
}`

Please resolve this issue ASAP.
Thanks.

ProgressRetail
APP ID: 98681

**Comment by ferhatelmas** [comment]
Thanks for your report. However, I need to invite you to [support](https://getstream.io/contact/support/) because it's not related to this .NET SDK (your request seems like from a client SDK due to `connection_id`) and it's related to your use-case and you can provide all details securely there.
