### ISSUE TITLE
Please add support to issued at time :) 

### ISSUE THREAD

**Issue by pawelgorka** [GetStream/stream-chat-net#76]
https://getstream.io/chat/docs/react/tokens_and_authentication/?language=javascript&q=duration#adding-iat-claim-to-token

https://github.com/GetStream/stream-chat-net/blob/cb4ae54058c685631c746f6697a87a7befb0e304/src/stream-chat-net/Client.cs#L77

**Comment by peterdeme** [comment]
@pawelgorka acknowledged, we'll update once it's done.

**Comment by peterdeme** [comment]
PR is open, I'll update here once it's released.

**Comment by peterdeme** [comment]
Released
